### ISSUE TITLE
Traces configuration is lost after restarting rabbitmq

### ISSUE THREAD

**Issue by xdrodger** [rabbitmq/rabbitmq-tracing#27]
Traces configuration is lost after restarting rabbitmq, is it a problem?
<img width="1454" alt="issue" src="https://user-images.githubusercontent.com/12492402/47984119-890f2e80-e110-11e8-9192-a7f3716747ac.png">

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
This plugin (much like tracing) isn't meant to be enabled at all times, so it uses transient storage for tracers and it doesn't survive node restart. The log files with trace results do, however.

**Comment by xdrodger** [comment]
thanks for you reply.
