### ISSUE TITLE
Distributed Tracing and Productionization

### ISSUE THREAD

**Issue by brycechesternewman** [rabbitmq/rabbitmq-tracing#29]
Hi,
We have lots of micro services that use RabbitMQ. In the context of Distributed Tracing there is allot of value in the tracer log header data to send we want to send to Splunk without the payload. One could argue why not add instrumentation for Distributed Tracing into the micro services and I argue that bugs and dropped message usually occur in the micro services easier then having one source of truth that a message was consumer or published using the Firehose logs. There is value in amq.rabbitmq.trace for debugging and development but for production the most value for us would be the outputs from the Firehose log. Is there any interest or reservations about in adding a feature to enable only logging to reduce CPU and Memory of amq.rabbitmq.trace? I would be more then happy to contribute.

Thank you.
Bryce

**Comment by michaelklishin** [comment]
Please post this to the mailing list. I'm not sure what you are suggestion but this plugin is not where most tracing or metric collection happens (or can happen). This is not specific enough to be an issue (by our team's standards). Thank you.

**Comment by michaelklishin** [comment]
To be clear, we are all for making it easier to integrate with tracing systems such as Zipkin. We have a new specialized "raw metrics" plugin for Prometheus in the works, for example, in addition to the metrics collectors and HTTP API we already have. So more than one solution for different needs is something we would consider.

**Comment by brycechesternewman** [comment]
Is the "raw metrics" plugin pushed to GitHub already? I would be interested.

Here is a simple example of what we are most interested in and I hope this clarifies better of what I am asking. Correlation_id first arrives in ap-image-transcode-request and then we want to know if correlation_id arrives in ap-image-transcode-response. Timing between when messages arrival in queues is nice to have but not as important as making sure they arrived at all.

Example logs from Firehose....

```
{"channel":569,"connection":"<omitted>:57358 -> <omitted>:5672","exchange":"dsa","node":"rabbit@<omitted>","payload":"","properties":{"correlation_id":"44c1f0a0-0062-bc11-0003-0169af52fbad","delivery_mode":2,"headers":{"GettyUserId":"<omitted>","MasterId":"1108612529","ObjectType":"Asset","SystemId":"<omitted>"},"message_id":"c71149f1-4de2-4256-bdf9-4b948aa28ad0","timestamp":1553526596},"queue":"none","routed_queues":["ap-image-transcode-request"],"routing_keys":["v1.ap.createrequest.image.medium"],"timestamp":"2019-03-25 15:09:56:609","type":"published","user":"assetpack","vhost":"dsa"}
```

```
{"channel":569,"connection":"<omitted>:57358 -> 1<omitted>:5672","exchange":"dsa","node":"rabbit@<omitted>","payload":"","properties":{"correlation_id":"44c1f0a0-0062-bc11-0003-0169af52fbad","delivery_mode":2,"headers":{"GettyUserId":"<omitted>","MasterId":"1108612529","ObjectType":"Asset","SystemId":"<omitted>"},"message_id":"c71149f1-4de2-4256-bdf9-4b948aa28ad0","timestamp":1553526596},"queue":"none","routed_queues":["ap-image-transcode-response"],"routing_keys":["v1.ap.createresponse.image.medium"],"timestamp":"2019-03-25 15:09:56:609","type":"published","user":"assetpack","vhost":"dsa"}
```

**Comment by michaelklishin** [comment]
A plugin similar to this one could do that. The biggest concern here, as before, is how to minimize the impact of this as with a naive implementation we'd double the load and/or introduce a point of failure in terms of event/Erlang message backlog accumulation.

The raw metrics plugin is technically open source but not yet ready to be announced. It simply exposes unaggregated samples for tools such as Grafana to aggregate. It's orthogonal to the kind of tracing you have in mind.

@gerhard @dcorbacho FYI.

**Comment by michaelklishin** [comment]
Also not clear to me: is there an emerging [de-facto] industry standard around on disk storage of tracing data? If so then this "new tracing" plugin should use it.

Let's move this to the mailing list.
